name: Yolo5 Microservice Deployment

on:
  push:
    paths:
      - 'yolo5/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: eu-west-2
#
#      - name: Set up Terraform
#        uses: hashicorp/setup-terraform@v1
#        with:
#          terraform_version: 1.2.0
#
#      - name: Initialize Terraform
#        run: terraform init
#        working-directory: terraform
#
#      - name: Apply Terraform
#        run: terraform apply -var-file=main.tfvars -auto-approve
#        working-directory: terraform

      - name: Read .env file
        id: read-env
        run: |
          export $(grep -v '^#' yolo5/.env | xargs)
          echo "YOLO5_IMG_NAME=${YOLO5_IMG_NAME}"
          echo "YOLO5_IMG_NAME=${YOLO5_IMG_NAME}" >> $GITHUB_ENV

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          echo "Building and pushing Docker image with tag: $IMAGE_TAG"
          docker build -t ${{ env.YOLO5_IMG_NAME }} .
          docker push ${{ env.YOLO5_IMG_NAME }}
        working-directory: yolo5

#  Deploy:
#    runs-on: ubuntu-latest
#    needs:
#      - Build
#
#    steps:
#      - name: Checkout the repo code
#        uses: actions/checkout@v2
#      - name: Deploy new version
#        run: |
#          # TODO your implementation here....
     
