name: Yolo5 Microservice Deployment

on:
  push:
    paths:
      - '**/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Read .env file
        id: read-env
        run: |
          export $(grep -v '^#' yolo5/.env | xargs)
          echo "YOLO5_IMG_NAME=${YOLO5_IMG_NAME}"
          echo "YOLO5_IMG_NAME=${YOLO5_IMG_NAME}" >> $GITHUB_ENV

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          echo "Building and pushing Docker image with tag: $IMAGE_TAG"
          docker build -t ${{ env.YOLO5_IMG_NAME }} .
          docker push ${{ env.YOLO5_IMG_NAME }}
        working-directory: yolo5
     
